FROM maven:3.9.6-eclipse-temurin-21 AS build
WORKDIR /app

# Copy root pom
COPY pom.xml .

# Copy ALL module pom.xml files so Maven can resolve the parent structure
COPY discovery-server/pom.xml discovery-server/
COPY user-service/pom.xml user-service/
COPY ride-service/pom.xml ride-service/
COPY payment-service/pom.xml payment-service/
COPY api-gateway/pom.xml api-gateway/

# Copy only payment-service source
COPY payment-service/src payment-service/src

# Build only payment-service
RUN mvn -pl payment-service -am clean package -Dmaven.test.skip=true

FROM eclipse-temurin:21-jre-alpine
WORKDIR /app
COPY --from=build /app/payment-service/target/*.jar app.jar
EXPOSE 8083
ENTRYPOINT ["java", "-jar", "app.jar"]